### ISSUE TITLE
Expose setSlide function

### ISSUE THREAD

**Issue by hyochan** [farbenmeer/react-spring-slider#100]
Could you expose `setSlide` method in [here](https://github.com/farbenmeer/react-spring-slider/blob/0428a354b98f6a94a7c829566ea658c9a3f799e6/src/index.tsx#L88)?

I'd like to manually slide even without dragging by clicking on the element outside the div.

Hope this could be applied soon or I'd like to fork this repo and use for myself :)

Thanks for all the work in advance.

**Comment by Tobi-mmt** [comment]
Hey @hyochan, thanks for your input.

We allready thought about this and you can set the acrive slide with the [activeIndex prop](https://github.com/farbenmeer/react-spring-slider/blob/0428a354b98f6a94a7c829566ea658c9a3f799e6/src/index.tsx#L60)

For example

```jsx
const foo = () => {
  const [sliderIndex, setSliderIndex] = useState(0)
  return (
    <button onClick={setSliderIndex(2)}>Move to third slide</button>
    <Slider activeIndex={slideIndex}>
      <MySlide />
      <MySlide />
      <MySlide />
    </Slider>
)}
```

**Comment by hyochan** [comment]
@Tobi-mmt Thanks for the feedback. I"ve already tried that but that only works at the initial state. When you swipe children around and call `setSliderIndex` it won't do anything.

**Comment by mstruebing** [comment]
That should be that story, right? 
https://farbenmeer.github.io/react-spring-slider/?path=/story/slider--with-activeindex-interval
https://github.com/farbenmeer/react-spring-slider/blob/master/src/index.stories.tsx#L63

What do you mean by "swipe children around" exactly?

**Comment by hyochan** [comment]
Sorry that I've not made it clear. To be specific, I want to tell you what I'm trying to build today.
I want to make my calendar carousel just like I did in flutter in [flutter_calendar_carousel](https://github.com/dooboolab/flutter_calendar_carousel).

If I use below code with `  const [activeIndex, setActiveIndex] = useState<number>(0);`, it won't do anything.
![image](https://user-images.githubusercontent.com/27461460/78972856-b18f2980-7b49-11ea-9484-06373a99bf95.png)

![vPjzdT54pA](https://user-images.githubusercontent.com/27461460/78973174-4e51c700-7b4a-11ea-86bd-42e8f845312e.gif)

Also, it'd be good if we can set index sometimes without animation and sometimes with animation.

**Comment by hyochan** [comment]
@mstruebing Would above make you clear now? Please tell me if anything isn't clear! Thanks.

**Comment by mstruebing** [comment]
Ah I can reproduce what you mean. It seems that this is indeed not working and it is a bug in my opinion so we should fix it.
Thank you for making it clear, we will try to provide a proper patch soonish.

**Comment by mstruebing** [comment]
I added the ability to add a property `setSlideCustom` which needs a function with the following signature: `(slide: number) => number` - because the bug I've thought was totally correct react behaviour.
I hope that will help you
