### ISSUE TITLE
Build an automated release process

### ISSUE THREAD

**Issue by mstruebing** [farbenmeer/react-spring-slider#11]
Currently, we release by `make release` and have some automated steps.
Maybe we can completely automate that in the future by every push on master.

This needs a bit of conception how to handle it exactly, generate changelog etc.

**Comment by Tobi-mmt** [comment]
Maybe we should use something like this https://github.com/conventional-changelog/standard-version#standard-version

**Comment by mstruebing** [comment]
With this we could also publish automatically on merge to master.
I would love to test it :)
Do you want to take it?

**Comment by Tobi-mmt** [comment]
Not before next week. So if you have time, go for it :)

**Comment by Tobi-mmt** [comment]
just for the record. I should do the following:

1. on push to master
2. generate changelog from commits
3. increase version in package(-lock).json
4. commit all together with the version tag
5. push to master againt
6. publish this tagged release to npm

Did i forgott something?

**Comment by Tobi-mmt** [comment]
If the following "simple" changelog is also okay..
```
Changelog:
* chore(deps): update node.js to v12.16.2 (#99) (0428a35)
* chore(deps): update dependency eslint-plugin-react-hooks to v3 (#98) (3ecb44b)
* chore(deps): update dependency prettier to v2 (#95) (a76fee6)
```

we can just use this tool:

https://github.com/release-it/release-it#changelog
