### ISSUE TITLE
The package at NPM doesn't match the project master

### ISSUE THREAD

**Issue by lironhl** [farbenmeer/react-spring-slider#113]
I'm pretty sure, the [npm package](https://www.npmjs.com/package/@farbenmeer/react-spring-slider) of the package lacks `setSlideCustom` option and more.
When will you update the package?

**Comment by mstruebing** [comment]
Hey @lironhl sorry to hear that.
We are pretty busy currently and have a pull requests which automates releases.
Once this is done the latest master is always released to npm.

As this issue doesn't have any more meaning I will close this now.

**Comment by mstruebing** [comment]
Hey @lironhl I just wanted to let you know that we now have autopublish ready and the current master should always reflect the published version on npm.

**Comment by lironhl** [comment]
That's awesome thanks!
