### ISSUE TITLE
Slides per view

### ISSUE THREAD

**Issue by endrits079** [farbenmeer/react-spring-slider#138]
This is one of the best sliders and easiest to use unfortunately it misses the feature to choose how many slides you wanna show at the same time, for example you have 3 slides you want to show 2 at same time (first and second) and on next (you want to show second and third)

**Comment by mstruebing** [comment]
Thank you for your kind words :1st_place_medal: 
I feel the need for that kind of feature and we already have an own issue for that: #80 but unfortunately no one worked on it yet.

If you want, you could try to implement that feature and provide a pull request.

However, thank you for that issue and as this is a duplicate I will close it.

**Comment by mstruebing** [comment]
This should be implemented by #140 now :)
