### ISSUE TITLE
Add prop to specify space between each slide

### ISSUE THREAD

**Issue by mcholewinski** [farbenmeer/react-spring-slider#148]
**Is your feature request related to a problem? Please describe.**
Right now the spaces between slides are responsive and in %. I would like to make this space static and the same at all screens.

**Describe the solution you'd like**
I think that adding a prop that takes space size in px/rem would be ideal. The prop should be optional and when it's not provided the slide space should be responsive.

**Describe alternatives you've considered**
I've tried accessing the slider CSS by '>' selector but didn't have any luck with it.

**Comment by mstruebing** [comment]
Hey @mcholewinski at first thank you for your issue it helps to make this component better :rocket: 

Could you elaborate a bit which spaces you mean? I think right now there is actually no space between the slides, each slide is takin 100% of the available witdth. If you have more than one slide in one view via the `slidesAtOnce` prop, there is no space too.
Either you mean some different spacing or I'm not really understanding what you are talking about.

**Comment by mcholewinski** [comment]
Oh, well I forgot to mention that I'm talking about the case when there are multiple slides displayed at once. The problem is the slide width, not space. Maybe it isn't a problem with the slider but with my custom slide component itself.

**Comment by mstruebing** [comment]
In that case, you should be able to give your single slide a specific width I think.
But what you probably rather want to do would be something like:

```js
<Slider>
 <SlideWrapper>
  <SlideContent/>
 </SlideWrapper>
 <SlideWrapper>
  <SlideContent/>
 </SlideWrapper>
 <SlideWrapper>
  <SlideContent/>
 </SlideWrapper>
</Slider>
```

Where `SlideWrapper` is some component taking 100% of the width and have a padding left and right and the `SlideContent` taking 100% width again.

I'm closing this issue as this is not a problem with the slider itself
