### ISSUE TITLE
BulletComponent key is null 

### ISSUE THREAD

**Issue by alainib** [farbenmeer/react-spring-slider#164]
Hello

**Describe the bug**

`Warning: BulletComponent: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://reactjs.org/link/special-props)`

**To Reproduce**
 
		  const BulletComponent = (props) => {
		    console.log(props);  // key is undefined is log
		    const { onClick, isActive, key } = props
		     
		    return (
		      <li
		        style={{
		          width: '35px',
		          height: '35px',
		          backgroundColor: 'white',
		          margin: '0',
		          padding: '5px 5px 2px 5px',
		          // I wanted to add left border radius to first element and right border radius element to make the whole white background look like rounded on corner a little
		        }}
		        onClick={onClick}
		      >
		        <div
		          style={{
		            width: '80%',
		            height: '80%',
		            margin: 'auto',
		            backgroundColor: isActive ? Config.colors.orange : Config.colors.darkBlue,
		            borderRadius: '50px',
		          }}
		        />
		      </li>
		    );
		  };

		<Slider hasBullets BulletComponent={BulletComponent} auto={0}> ... 

**Expected behavior**

 I wanted to add left border radius to first element and right border radius to last element, so the whole white background look like rounded on corner a little. maybe not the best approche , better to add a custom styled container for BulletComponent but not possible for now, or i didn't found it

 

**Desktop (please complete the following information):**
  - Device: macbook 
  - Browser chrome, safari
  - Version "1.3.3"

**Comment by mstruebing** [comment]
`key` is a react property which is not passed on, so you can not access it inside your custom bullet.
