### ISSUE TITLE
add custom style to BulletComponent container

### ISSUE THREAD

**Issue by alainib** [farbenmeer/react-spring-slider#165]
hello

is there a way to add custom style to `BulletComponent` parent container  ?

For example  i want to replace the `margin :'15px 0'` by `margin :'0px'` and add white background with border radius

my actual code : 

 
		const BulletComponent = ({ onClick, isActive, key }) => { 
			return (
				<li
					style={{
						width: '35px',	height: '35px', backgroundColor: 'white',
						margin: '0', padding: '12px 1px 0px 6px', 
					}}
					onClick={onClick}
				>
					<div
						style={{
							width: '60%',	height: '60%',
							margin: 'auto',borderRadius: '50px',
							backgroundColor: isActive ? Config.colors.orange : Config.colors.darkBlue,
						}}
					/>
				</li>
			);
		};
		

		<Slider hasBullets BulletComponent={BulletComponent} BulletComponentParentStyle={{margin:'0px !important '}}>

Top : what i have now
Bottom : what i try to do

<img width="635" alt="compare" src="https://user-images.githubusercontent.com/7910081/102509842-4a862500-4087-11eb-9b32-8e97d443a100.png">

thanks

**Comment by mstruebing** [comment]
Hey thank you for your issue, unfortunately, that is not possible currently.
I also honestly don't think this is a must-have feature.

If you think that is really needed feel free to open a PR but please keep in mind to have meaningful defaults
