### ISSUE TITLE
More responsive slide action, or more start/stop trigger flexibility

### ISSUE THREAD

**Issue by ajbraudev** [farbenmeer/react-spring-slider#204]
Would love to be able to make sliding with your thumb easier on a mobile phone

**Comment by Tobi-mmt** [comment]
hey @ajbraudev thanks for your suggestion. 🙂

Can you give an example how the feature you wish should look like or which behavior should be customizable?

For example:
- the time between the touch event ends and the slide snips to it's position should be customizable
- dragging with two fingers should move to the last slide
- the way a finger has to slide over the screen until the next slide appears should be lower/higher
- ...

**Comment by Tobi-mmt** [comment]
Since there is no detailed information of the purpose of this ticket I will close it.
Feel free to create a new one or reopen if there are more details.
