### ISSUE TITLE
Our documentation should not promote defining components in a render function

### ISSUE THREAD

**Issue by mismosmi** [farbenmeer/react-spring-slider#254]
**Describe the bug**
The main example in the README defined the Arrow and other utility components within the main App-component.
This is a really bad antipattern.

**To Reproduce**
Take a look at the README

**Expected behavior**
The README should not promote antipatterns

**Additional context**
This is a _large_ issue template :grin:

**Comment by mismosmi** [comment]
Don't get me wrong, I'll fix this myself, this is just a reminder to myself...

**Comment by Tobi-mmt** [comment]
So you just want to replace `App` with e.g. `MySlider` in the readme?

**Comment by mismosmi** [comment]
[This](https://github.com/farbenmeer/react-spring-slider/pull/255) is what I mean :)
