### ISSUE TITLE
Correct releasing documentation in `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by mstruebing** [farbenmeer/react-spring-slider#84]
Currently, the docs state that you only need to run `make release`.
This isn't fully true as we have branch protecting rules which forbid to push directly to master but in the release process, we push changes to master.

Either, update the docs correctly or think of an alternative way to release.
Maybe this is somewhat connected to #11

**Comment by Tobi-mmt** [comment]
Maybe we should use something like this https://github.com/conventional-changelog/standard-version#standard-version
