### ISSUE TITLE
Add a way to disable the sliding functionality and just render the children

### ISSUE THREAD

**Issue by beamercola** [farbenmeer/react-spring-slider#96]
For instance, on an e-commerce site, when it's on mobile i want to show a slideshow, but on desktop i want all the images stacked so I can scroll them.

**Comment by mstruebing** [comment]
Hey @beamercola, sorry for the late reply but thank you for your issue.

I don't think that this should be the duty of the slider, that should rather be handled by a parent component which should show the slider on mobile and on desktop just a collection of images.

So I'll close this issue.
